[project]
name = "sqlmodelservice"
description = "A generic service layer on top of SQLModel for conveniently creating APIs with frameworks like FastAPI."
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Peter Volf", email = "do.volfp@gmail.com" }]
dynamic = ["version"]
license = { text = "MIT" }
dependencies = [
    "pydantic>=2.11",
    "sqlmodel>=0.0.38,<0.1",
]

[dependency-groups]
dev = [
    "mkdocstrings>=1.0.4",
    "mkdocstrings-python>=2.0.3",
    "mypy>=1.20.1",
    "poethepoet>=0.44.0",
    "psycopg>=3.3.3",
    "pytest>=9.0.3",
    "pytest-random-order>=1.2.0",
    "ruff>=0.15.10",
    "testcontainers[postgres]>=4.14.2",
    "zensical>=0.0.33",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project.urls]
Homepage = "https://github.com/volfpeter/sqlmodelservice"
Documentation = "https://volfpeter.github.io/sqlmodelservice"

[tool.mypy]
strict = true
show_error_codes = true

[tool.pdm.version]
source = "file"
path = "sqlmodelservice/__init__.py"

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.pytest.ini_options]
addopts = "--random-order"

[tool.ruff]
line-length = 118
exclude = [
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "dist",
    "docs",
]
lint.select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "S",  # flake8-bandit - we must ignore these rules in tests
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*" = ["S101"]  # S101: use of assert detected

[tool.poe.tasks]
serve-docs = "zensical serve"

format = "ruff format . --check"
format-fix = "ruff format ."

lint = "ruff check ."
lint-fix = "ruff check . --fix"

mypy = "mypy ."

check.sequence = ["format", "lint", "mypy"]
check.ignore_fail = "return_non_zero"

test = "python -m pytest tests"
