name: Publish

on:
  release:
    types:
      - created

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          # Issue ref: https://github.com/actions/setup-python/issues/436
          # cache: "pip"
          cache-dependency-path: pyproject.toml
          python-version-file: pyproject.toml

      - name: Install poetry
        run: python3 -m pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Build package to dist/
        run: poetry build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
